config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  namespace :admin do
    resources :achievements do
      member do
        get 'control', to: 'achievements#control'
        patch 'patch', to: 'achievements#patch'
      end
    end
    resources :props do
      member do
        get 'prop_upload_success', to: 'prop_upload#handle_upload_success'
        get 'prop_control', to: 'props#control'
        patch 'patch', to: 'props#patch'
      end
    end
    resources :chapters do
      collection do
        put 'reorder' => 'chapters#reorder', as: :reorder
      end
    end
  end
  get '/admin' => 'admin#index', as: :admin

end

app/models/achievement.rb
# == Schema Information
#
# Table name: achievements
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  censored_description :string(255)
#  full_description     :string(255)
#  image_url            :string(255)
#  tags                 :string(255)      default([]), is an Array
#  secret               :boolean          default(FALSE)
#  created_at           :datetime
#  updated_at           :datetime
#  chapter_id           :integer
#  won_by               :string(255)
#  won_at               :datetime
#
# Indexes
#
#  index_achievements_on_chapter_id  (chapter_id)
#  index_achievements_on_tags        (tags)
#

class Achievement < ActiveRecord::Base
  validates :name, :full_description, :chapter_id, presence: true

  belongs_to :chapter

  default_scope { order(:name) }

  def is_won
    !!won_at
  end
end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id    :integer          not null, primary key
#  name  :string(255)
#  index :integer
#

class Chapter < ActiveRecord::Base
  validates :name, presence: true

  has_many :achievements, dependent: :destroy
  has_many :props, dependent: :destroy

  default_scope { order(:index) }

  def self.reorder(ids)
    indices = {}

    ids.each_with_index do |id, i|
      indices[id.to_i] = i
    end

    all.each do |model|
      model.update_attribute(:index, indices[model.id] || indices.count)
    end
  end
end

app/models/prop.rb
# == Schema Information
#
# Table name: props
#
#  id            :integer          not null, primary key
#  attached_file :string(255)
#  name          :string(255)
#  description   :string(255)
#  found         :boolean
#  chapter_id    :integer
#  tags          :string(255)      default([]), is an Array
#  created_at    :datetime
#  updated_at    :datetime
#
# Indexes
#
#  index_props_on_chapter_id  (chapter_id)
#  index_props_on_tags        (tags)
#

class Prop < ActiveRecord::Base
  validates :name, :description, presence: true

  mount_uploader :attached_file, FileUploader

  belongs_to :chapter

  default_scope { order(:name) }
  scope :found, -> { where(found: true) }

  def is_found
    found
  end
end

app/controllers/admin/achievements_controller.rb
module Admin
  class AchievementsController < AdminController

    def index
      @achievements = Achievement.all
    end

    def new
      @achievement = Achievement.new
    end

    def create
      # render text: params.inspect and return
      @achievement = AchievementBuilder.build params[:achievement]
      redirect_to admin_chapter_path(@achievement.chapter)
    end

    def show
      @achievement = Achievement.find params[:id]
    end

    def edit
      @achievement = Achievement.find params[:id]
    end

    def update
      # render text: params.inspect and return
      @achievement = Achievement.find params[:id]
      @achievement = AchievementBuilder.update @achievement, params[:achievement]
      respond_with :admin, @achievement
    end

    def control
      @achievement = Achievement.find params[:id]
      render layout: false
    end

    def patch
      @achievement = Achievement.find params[:id]
      AchievementUpdater.update @achievement, params[:achievement]
      redirect_to admin_chapter_path(@achievement.chapter)
    end

    def destroy
      @achievement = Achievement.find params[:id]
      @achievement.destroy
      redirect_to admin_path
    end

  end
end

app/controllers/admin/chapters_controller.rb
module Admin
  class ChaptersController < AdminController

    def index
      @chapters = Chapter.all
    end

    def new
      @chapter = Chapter.new
    end

    def create
      @chapter = ChapterBuilder.build params[:chapter]
      respond_with :admin, @chapter
    end

    def show
      @chapter = Chapter.find params[:id]
    end

    def edit
      @chapter = Chapter.find params[:id]
    end

    def update
      @chapter = Chapter.find params[:id]
      @chapter = ChapterBuilder.update @chapter, params[:chapter]
      respond_with :admin, @chapter
    end

    def destroy
      @chapter = Chapter.find params[:id]
      @chapter.destroy
      redirect_to admin_path
    end

    def reorder
      Chapter.reorder(params[:ids])
      head 204
    end

  end
end

app/controllers/admin/prop_upload_controller.rb
module Admin
  class PropUploadController < AdminController
    def handle_upload_success
      @prop = Prop.find params[:id]
      @prop.update_attribute :key, params[:key]
      redirect_to admin_chapter_url(@prop.chapter_id)
    end
  end
end

app/controllers/admin/props_controller.rb
module Admin
  class PropsController < AdminController

    def index
      @props = Prop.all
    end

    def new
      @prop = Prop.new
    end

    def create
      # render text: params[:prop].inspect and return
      @prop = PropBuilder.build params[:prop]
      redirect_to admin_chapter_path(@prop.chapter)
    end

    def show
      @prop = Prop.find params[:id]
      @uploader = @prop.attached_file
      @uploader.success_action_redirect = prop_upload_success_admin_prop_url(@prop)
    end

    def edit
      @prop = Prop.find params[:id]
    end

    def update
      # render text: params.inspect and return
      @prop = Prop.find params[:id]
      @prop = PropBuilder.update @prop, params[:prop]
      respond_with :admin, @prop
    end

    def control
      @prop = Prop.find params[:id]
      render layout: false
    end

    def patch
      @prop = Prop.find params[:id]
      PropUpdater.update @prop, params[:prop]
      redirect_to admin_chapter_path(@prop.chapter)
    end

    def destroy
      @prop = Prop.find params[:id]
      @prop.destroy
      redirect_to admin_path
    end

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "mhw", password: ENV['ADMIN_PASSWORD']

  def index
    @chapters     = Chapter.all
    @achievements = Achievement.unscoped.includes(:chapter).order("chapters.index, achievements.name").all
    @props        = Prop.unscoped.includes(:chapter).order("chapters.index, props.name").all
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @chapters = Chapter.includes(:achievements).includes(:props).all
  end

end

app/helpers/achievements_helper.rb
module AchievementsHelper

  def public_description_for_achievement achievement
    if achievement.won_at
      achievement.full_description
    elsif achievement.secret?
      "[ A SECRET MAN WAS NOT MEANT TO KNOW ]"
    elsif achievement.censored_description.blank?
      achievement.full_description
    else
      achievement.censored_description
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_correct_key_goddammit_responder_you_suck key
    if key.to_s == 'notice'
      :success
    elsif key.to_s == 'alert'
      :danger
    else
      key
    end
  end
end

app/views/admin/achievements/_form.html.slim
= form_for achievement, url: path, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :chapter_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :chapter_id, Chapter.all.collect {|c| [ c.name, c.id ] }, class: 'form-control'

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control', placeholder: 'Name', required: true

  .form-group
    = f.label :censored_description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :censored_description, class: 'form-control'

  .form-group
    = f.label :full_description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :full_description, class: 'form-control', required: true

  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        = f.label :secret
          = f.check_box :secret
          | Secret?

  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        = f.label :is_won
          = f.check_box :is_won
          | Won?

  .form-group
    = f.label :won_by, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :won_by, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-success'

app/views/admin/achievements/control.html.slim
.modal-header
  h4.modal-title Edit #{@achievement.name}

= form_for @achievement, url: patch_admin_achievement_path(@achievement), html: { class: 'form-horizontal' } do |f|
  .modal-body
    .form-group
      .col-sm-offset-2.col-sm-10
        .checkbox
          = f.label :is_won
            = f.check_box :is_won
            | Won?

    .form-group
      = f.label :won_by, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :won_by, class: 'form-control'

  .modal-footer
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-success'

app/views/admin/achievements/edit.html.slim
h2 Edit #{@achievement.name}

= render 'form', achievement: @achievement, path: admin_achievement_path(@achievement)

.row
  .well
    = link_to "&laquo; View".html_safe, admin_achievement_path(@achievement), class: 'btn btn-primary'
    '
    = link_to "Delete", admin_achievement_path(@achievement), class: 'btn btn-danger', method: :delete

app/views/admin/achievements/new.html.slim
h2 New Achievement

= render 'form', achievement: @achievement, path: admin_achievements_path

.row
  .well
    = link_to "Nevermind", admin_path, class: 'btn btn-primary'

app/views/admin/achievements/show.html.slim
h2 #{@achievement.chapter.name} &ndash; #{@achievement.name}

- if @achievement.won_at
  h4 Won by #{@achievement.won_by} on #{@achievement.won_at.to_s(:ymd)}

table.table
  tr
    th Censored
    th Full
    th Secret?
  tr
    td #{@achievement.censored_description || ''}
    td = @achievement.full_description
    td = @achievement.secret? ? 'Yes' : 'No'

.row
  .well
    = link_to "&laquo; Admin".html_safe, admin_path, class: 'btn btn-primary'
    '
    = link_to "Edit", edit_admin_achievement_path(@achievement), class: 'btn btn-warning'

app/views/admin/chapters/_form.html.slim
= form_for chapter, url: path, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control', placeholder: 'Name', required: true

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-success'

app/views/admin/chapters/edit.html.slim
h2 Edit #{@chapter.name}

= render 'form', chapter: @chapter, path: admin_chapter_path(@chapter)

.row
  .well
    = link_to "Nevermind", admin_chapter_path(@chapter), class: 'btn btn-primary'
    '
    = link_to "Delete", admin_chapter_path(@chapter), class: 'btn btn-danger', method: :delete

app/views/admin/chapters/index.html.slim
h2 Chapters

- if @chapters.empty?
  .well None!
- else
  ul
    - @chapters.each do |chapter|
      li = link_to chapter.name, edit_admin_chapter_path(chapter)

= link_to "New Chapter", new_admin_chapter_path

app/views/admin/chapters/new.html.slim
h2 New Chapter

= render 'form', chapter: @chapter, path: admin_chapters_path

.row
  .well
    = link_to "Nevermind", admin_path, class: 'btn btn-primary'

app/views/admin/chapters/show.html.slim
h2 #{@chapter.name}

h3 Achievements

- if @chapter.achievements.empty?
  .well
    ' No achievements!

- else
  table.table.table-striped
    thead
      tr
        th Name
        th Censored
        th Full
        th Secret?
        th Won?
        th Admin
    tbody
      - @chapter.achievements.each do |ach|
        tr
          td = link_to ach.name, edit_admin_achievement_path(ach)
          td = ach.censored_description
          td = ach.full_description
          td = ach.secret? ? 'Y' : 'N'
          td = ach.won_at ? 'Y' : 'N'
          td
            a.btn.btn-default data-toggle="modal" data-target="#achievement-modal" data-keyboard="true" href="#{control_admin_achievement_path(ach)}" Admin

#achievement-modal.modal.fade tabindex='-1'
  .modal-dialog
    .modal-content
      ' Loading achievement...

h3 Props

- if @chapter.props.empty?
  .well
    ' No props!

- else
  table.table.table-striped
    thead
      tr
        th Name
        th Link
        th Found
        th Admin
    tbody
      - @chapter.props.each do |prop|
        tr
          td = link_to prop.name, admin_prop_path(prop)
          td = link_to "Download link", prop.attached_file.url.gsub("%2520", "+") if prop.attached_file?
          td = prop.found ? 'Yes' : 'No'
          td
            a.btn.btn-default data-toggle="modal" data-target="#prop-modal" data-keyboard="true" href="#{prop_control_admin_prop_path(prop)}" Admin

#prop-modal.modal.fade tabindex='-1'
  .modal-dialog
    .modal-content
      ' Loading prop...

.row
  .well
    = link_to "Admin", admin_path, class: 'btn btn-primary'
    '
    = link_to "Edit", edit_admin_chapter_path(@chapter), class: 'btn btn-warning'
    '
    = link_to "New Achievement", new_admin_achievement_path, class: 'btn btn-default'
    '
    = link_to "New Prop", new_admin_prop_path, class: 'btn btn-default'

app/views/admin/index.html.slim
h2 Admin

.row
  .col-md-12
    h4 Chapters

    - if @chapters.empty?
      .well None!
    - else
      ul.sortable.nav.nav-pills.nav-stacked
        - @chapters.each do |chapter|
          li data-id=chapter.id
            = link_to admin_chapter_path(chapter) do
              span.pull-right
                ' Achievements: #{chapter.achievements.count} Props: #{chapter.props.count}
              = chapter.name

    .well
      = link_to "New Chapter", new_admin_chapter_path, class: "btn btn-primary"

app/views/admin/props/_form.html.slim
= form_for prop, url: path, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :chapter_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :chapter_id, Chapter.all.collect {|c| [ c.name, c.id ] }, class: 'form-control'

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control', placeholder: 'Name', required: true

  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :description, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
        = f.label :found
          = f.check_box :found
          | Won?

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-success'

app/views/admin/props/control.html.slim
.modal-header
  h4.modal-title Edit #{@prop.name}

= form_for @prop, url: patch_admin_prop_path(@prop), html: { class: 'form-horizontal' } do |f|
  .modal-body
    .form-group
      .col-sm-offset-2.col-sm-10
        .checkbox
          = f.label :found
            = f.check_box :found
            | Won?

  .modal-footer
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-success'

app/views/admin/props/edit.html.slim
h2 Edit #{@prop.name}

= render 'form', prop: @prop, path: admin_prop_path(@prop)

.row
  .well
    = link_to "&laquo; View".html_safe, admin_prop_path(@prop), class: 'btn btn-primary'
    '
    = link_to "Delete", admin_prop_path(@prop), class: 'btn btn-danger', method: :delete

app/views/admin/props/new.html.slim
h2 New Prop

= render 'form', prop: @prop, path: admin_props_path

.row
  .well
    = link_to "Nevermind", admin_path, class: 'btn btn-primary'

app/views/admin/props/show.html.slim
h2 #{@prop.chapter.name} &ndash; #{@prop.name}

table.table
  tr
    th Description
    th Link
  tr
    td = @prop.description
    td = link_to(@prop.name, @prop.attached_file.url) if @prop.attached_file

- unless @prop.attached_file?
  h4 Upload Attachment

  = direct_upload_form_for @uploader, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label :attached_file, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.file_field :attached_file, class: 'form-control'

    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit 'Upload File', class: 'btn btn-success'

.row
  .well
    = link_to "&laquo; Admin".html_safe, admin_path, class: 'btn btn-primary'
    '
    = link_to "Edit", edit_admin_prop_path(@prop), class: 'btn btn-warning'
    '
    = link_to "Delete", admin_prop_path(@prop), class: 'btn btn-danger', method: :delete

app/views/landing/index.html.slim
.row
  p Achievement status: #{Achievement.where.not(won_at: nil).count} / #{Achievement.count}
  p Props found: #{Prop.where(found: true).count}

.row
  .col-md-3
    ul.nav.nav-pills.nav-stacked data-spy="affix" data-offset-top="0"
      - @chapters.each do |chapter|
        li = link_to chapter.name, "#chapter-#{chapter.id}"

  .col-md-9
    - @chapters.each do |chapter|

      h4
        .pull-right
          #{chapter.achievements.where.not(won_at: nil).count} / #{chapter.achievements.count}
        #{chapter.name}
        a.no-link name="chapter-#{chapter.id}"

      table.table.table-striped.table-hover.table-achievements
        tr
          th Name
          th.description Description
          th.won-by Won By

        - chapter.achievements.each do |ach|
          tr class="#{ach.won_at ? 'success' : ''}"
            td = ach.name
            td.description = public_description_for_achievement(ach)
            td.won-by = ach.won_by

      - if chapter.props.where(found: true).count > 0
        h5 Props

        table.table.table-striped.table-hover.table-props
          tr
            th Name
            th Description
            th Link

          - chapter.props.where(found: true).each do |prop|
            tr
              td = prop.name
              td = prop.description
              td = link_to "Download", prop.attached_file.url.gsub("%2520", "+"), target: '_blank'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Achievements
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          = link_to "Achievements", root_path, class: 'navbar-brand'

    section.container
      = render 'shared/flash_messages'

      = yield

app/views/shared/_flash_messages.html.slim
- flash.each do |key, message|
  - correct_key = get_correct_key_goddammit_responder_you_suck key
  div class="alert alert-#{correct_key} alert-dismissable"
    button.close data-dismiss="alert" type="button" &times;
    strong #{correct_key.capitalize}:
    |  #{message}